/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: kingillager (https://sketchfab.com/kingillager)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sculk-octopus-dd769ccd21664565b365e38db4a0b3a1
Title: Sculk octopus
*/

import React, { useRef , useEffect} from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

import scene from '../assets/3d/octopus.glb'

const Octopus = ({currentAnimation, ...props}) => {

  const group = useRef()
  const { nodes, materials, animations } = useGLTF(scene)
  const { actions } = useAnimations(animations, group)

  useEffect(()=>{
    Object.values(actions).forEach((action)=> action.stop());

    if(actions[currentAnimation]){
        actions[currentAnimation].play()
    }
  },[actions,currentAnimation])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="_179">
                <group name="sculkoctopus_178">
                  <group name="cube_0">
                    <mesh
                      name="Object_6"
                      castShadow
                      receiveShadow
                      geometry={nodes.Object_6.geometry}
                      material={materials.material_0}
                    />
                  </group>
                  <group name="sculk_2">
                    <group name="cube_1">
                      <mesh
                        name="Object_9"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_9.geometry}
                        material={materials.material_0}
                      />
                    </group>
                  </group>
                  <group name="hands_163">
                    <group
                      name="hand1_22"
                      position={[0.313, 0.063, -0.25]}
                      rotation={[0, -0.611, 0]}>
                      <group name="cube_3" position={[-0.313, -0.063, 0.25]}>
                        <mesh
                          name="Object_13"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_13.geometry}
                          material={materials.material_0}
                        />
                      </group>
                      <group
                        name="hand1piece_19"
                        position={[0, 0, -0.25]}
                        rotation={[0.35, -0.082, 0.03]}>
                        <group name="cube_4" position={[-0.313, -0.063, 0.5]}>
                          <mesh
                            name="Object_16"
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_16.geometry}
                            material={materials.material_0}
                          />
                        </group>
                        <group
                          name="hand1pieceaddon_16"
                          position={[0, 0, -0.25]}
                          rotation={[Math.PI / 6, 0, 0]}>
                          <group name="cube_5" position={[-0.313, -0.063, 0.563]}>
                            <mesh
                              name="Object_19"
                              castShadow
                              receiveShadow
                              geometry={nodes.Object_19.geometry}
                              material={materials.material_0}
                            />
                          </group>
                          <group
                            name="hand1pieceaddonpart_13"
                            position={[0, 0, -0.25]}
                            rotation={[Math.PI / 4, 0, 0]}>
                            <group name="cube_6" position={[-0.313, -0.063, 0.813]}>
                              <mesh
                                name="Object_22"
                                castShadow
                                receiveShadow
                                geometry={nodes.Object_22.geometry}
                                material={materials.material_0}
                              />
                            </group>
                            <group
                              name="hand1pieceaddonpartend_10"
                              position={[0, 0, -0.188]}
                              rotation={[Math.PI / 3, 0, 0]}>
                              <group name="cube_7" position={[-0.313, -0.063, 1]}>
                                <mesh
                                  name="Object_25"
                                  castShadow
                                  receiveShadow
                                  geometry={nodes.Object_25.geometry}
                                  material={materials.material_0}
                                />
                              </group>
                              <group name="hand1pieceaddonpartendsculk_9">
                                <group name="cube_8">
                                  <mesh
                                    name="Object_28"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Object_28.geometry}
                                    material={materials.material_0}
                                  />
                                </group>
                              </group>
                            </group>
                            <group
                              name="hand1pieceaddonpartsculk_12"
                              position={[-0.063, 1.125, 0.188]}>
                              <group name="cube_11" position={[0.063, -1.125, -0.188]}>
                                <mesh
                                  name="Object_31"
                                  castShadow
                                  receiveShadow
                                  geometry={nodes.Object_31.geometry}
                                  material={materials.material_0}
                                />
                              </group>
                            </group>
                          </group>
                          <group name="hand1pieceaddonsculk_15" position={[-0.125, 0.563, 0.625]}>
                            <group name="cube_14" position={[0.125, -0.563, -0.625]}>
                              <mesh
                                name="Object_34"
                                castShadow
                                receiveShadow
                                geometry={nodes.Object_34.geometry}
                                material={materials.material_0}
                              />
                            </group>
                          </group>
                        </group>
                        <group name="hand1piecesculk_18">
                          <group name="cube_17">
                            <mesh
                              name="Object_37"
                              castShadow
                              receiveShadow
                              geometry={nodes.Object_37.geometry}
                              material={materials.material_0}
                            />
                          </group>
                        </group>
                      </group>
                      <group name="hand1sculk_21" position={[-0.313, -0.063, 0.25]}>
                        <group name="cube_20">
                          <mesh
                            name="Object_40"
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_40.geometry}
                            material={materials.material_0}
                          />
                        </group>
                      </group>
                    </group>
                    <group
                      name="hand2_42"
                      position={[0.125, 0.063, -0.313]}
                      rotation={[0, -0.262, 0]}>
                      <group name="cube_23" position={[-0.313, -0.063, 0.25]}>
                        <mesh
                          name="Object_43"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_43.geometry}
                          material={materials.material_0}
                        />
                      </group>
                      <group
                        name="hand1piece2_39"
                        position={[0, 0, -0.25]}
                        rotation={[Math.PI / 9, 0, 0]}>
                        <group name="cube_24" position={[-0.313, -0.063, 0.5]}>
                          <mesh
                            name="Object_46"
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_46.geometry}
                            material={materials.material_0}
                          />
                        </group>
                        <group
                          name="hand1pieceaddon2_36"
                          position={[0, 0, -0.25]}
                          rotation={[Math.PI / 6, 0, 0]}>
                          <group name="cube_25" position={[-0.313, -0.063, 0.563]}>
                            <mesh
                              name="Object_49"
                              castShadow
                              receiveShadow
                              geometry={nodes.Object_49.geometry}
                              material={materials.material_0}
                            />
                          </group>
                          <group
                            name="hand1pieceaddonpart2_33"
                            position={[0, 0, -0.25]}
                            rotation={[Math.PI / 4, 0, 0]}>
                            <group name="cube_26" position={[-0.313, -0.063, 0.813]}>
                              <mesh
                                name="Object_52"
                                castShadow
                                receiveShadow
                                geometry={nodes.Object_52.geometry}
                                material={materials.material_0}
                              />
                            </group>
                            <group
                              name="hand1pieceaddonpartend2_30"
                              position={[0, 0, -0.188]}
                              rotation={[Math.PI / 3, 0, 0]}>
                              <group name="cube_27" position={[-0.313, -0.063, 1]}>
                                <mesh
                                  name="Object_55"
                                  castShadow
                                  receiveShadow
                                  geometry={nodes.Object_55.geometry}
                                  material={materials.material_0}
                                />
                              </group>
                              <group name="hand1pieceaddonpartendsculk2_29">
                                <group name="cube_28">
                                  <mesh
                                    name="Object_58"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Object_58.geometry}
                                    material={materials.material_0}
                                  />
                                </group>
                              </group>
                            </group>
                            <group name="hand1pieceaddonpartsculk2_32" position={[0, 0.938, 0.313]}>
                              <group name="cube_31" position={[0, -0.938, -0.313]}>
                                <mesh
                                  name="Object_61"
                                  castShadow
                                  receiveShadow
                                  geometry={nodes.Object_61.geometry}
                                  material={materials.material_0}
                                />
                              </group>
                            </group>
                          </group>
                          <group name="hand1pieceaddonsculk2_35" position={[-0.063, 0.563, 0.563]}>
                            <group name="cube_34" position={[0.063, -0.563, -0.563]}>
                              <mesh
                                name="Object_64"
                                castShadow
                                receiveShadow
                                geometry={nodes.Object_64.geometry}
                                material={materials.material_0}
                              />
                            </group>
                          </group>
                        </group>
                        <group name="hand1piecesculk2_38" position={[0.188, 0, 0.063]}>
                          <group name="cube_37" position={[-0.188, 0, -0.063]}>
                            <mesh
                              name="Object_67"
                              castShadow
                              receiveShadow
                              geometry={nodes.Object_67.geometry}
                              material={materials.material_0}
                            />
                          </group>
                        </group>
                      </group>
                      <group name="hand1sculk2_41" position={[-0.313, -0.063, 0.25]}>
                        <group name="cube_40" position={[0.188, 0, 0.063]}>
                          <mesh
                            name="Object_70"
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_70.geometry}
                            material={materials.material_0}
                          />
                        </group>
                      </group>
                    </group>
                    <group
                      name="hand3_62"
                      position={[-0.125, 0.063, -0.313]}
                      rotation={[0, 0.262, 0]}>
                      <group name="cube_43" position={[-0.313, -0.063, 0.25]}>
                        <mesh
                          name="Object_73"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_73.geometry}
                          material={materials.material_0}
                        />
                      </group>
                      <group
                        name="hand1piece3_59"
                        position={[0, 0, -0.25]}
                        rotation={[Math.PI / 9, 0, 0]}>
                        <group name="cube_44" position={[-0.313, -0.063, 0.5]}>
                          <mesh
                            name="Object_76"
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_76.geometry}
                            material={materials.material_0}
                          />
                        </group>
                        <group
                          name="hand1pieceaddon3_56"
                          position={[0, 0, -0.25]}
                          rotation={[Math.PI / 6, 0, 0]}>
                          <group name="cube_45" position={[-0.313, -0.063, 0.563]}>
                            <mesh
                              name="Object_79"
                              castShadow
                              receiveShadow
                              geometry={nodes.Object_79.geometry}
                              material={materials.material_0}
                            />
                          </group>
                          <group
                            name="hand1pieceaddonpart3_53"
                            position={[0, 0, -0.25]}
                            rotation={[Math.PI / 4, 0, 0]}>
                            <group name="cube_46" position={[-0.313, -0.063, 0.813]}>
                              <mesh
                                name="Object_82"
                                castShadow
                                receiveShadow
                                geometry={nodes.Object_82.geometry}
                                material={materials.material_0}
                              />
                            </group>
                            <group
                              name="hand1pieceaddonpartend3_50"
                              position={[0, 0, -0.188]}
                              rotation={[Math.PI / 3, 0, 0]}>
                              <group name="cube_47" position={[-0.313, -0.063, 1]}>
                                <mesh
                                  name="Object_85"
                                  castShadow
                                  receiveShadow
                                  geometry={nodes.Object_85.geometry}
                                  material={materials.material_0}
                                />
                              </group>
                              <group name="hand1pieceaddonpartendsculk3_49">
                                <group name="cube_48">
                                  <mesh
                                    name="Object_88"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Object_88.geometry}
                                    material={materials.material_0}
                                  />
                                </group>
                              </group>
                            </group>
                            <group
                              name="hand1pieceaddonpartsculk3_52"
                              position={[0.063, 1.063, 0.313]}>
                              <group name="cube_51" position={[-0.063, -1.063, -0.313]}>
                                <mesh
                                  name="Object_91"
                                  castShadow
                                  receiveShadow
                                  geometry={nodes.Object_91.geometry}
                                  material={materials.material_0}
                                />
                              </group>
                            </group>
                          </group>
                          <group name="hand1pieceaddonsculk3_55" position={[0, 0.5, 0.563]}>
                            <group name="cube_54" position={[0, -0.5, -0.563]}>
                              <mesh
                                name="Object_94"
                                castShadow
                                receiveShadow
                                geometry={nodes.Object_94.geometry}
                                material={materials.material_0}
                              />
                            </group>
                          </group>
                        </group>
                        <group name="hand1piecesculk3_58" position={[0.438, 0, 0.063]}>
                          <group name="cube_57" position={[-0.438, 0, -0.063]}>
                            <mesh
                              name="Object_97"
                              castShadow
                              receiveShadow
                              geometry={nodes.Object_97.geometry}
                              material={materials.material_0}
                            />
                          </group>
                        </group>
                      </group>
                      <group name="hand1sculk3_61" position={[-0.313, -0.063, 0.25]}>
                        <group name="cube_60" position={[0.438, 0, 0.063]}>
                          <mesh
                            name="Object_100"
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_100.geometry}
                            material={materials.material_0}
                          />
                        </group>
                      </group>
                    </group>
                    <group
                      name="hand4_82"
                      position={[-0.313, 0.063, -0.25]}
                      rotation={[0, 0.611, 0]}>
                      <group name="cube_63" position={[-0.324, -0.063, 0.286]}>
                        <mesh
                          name="Object_103"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_103.geometry}
                          material={materials.material_0}
                        />
                      </group>
                      <group
                        name="hand1piece4_79"
                        position={[0, 0, -0.25]}
                        rotation={[0.35, 0.082, -0.03]}>
                        <group name="cube_64" position={[-0.716, -0.048, -0.492]}>
                          <mesh
                            name="Object_106"
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_106.geometry}
                            material={materials.material_0}
                          />
                        </group>
                        <group
                          name="hand1pieceaddon4_76"
                          position={[0, 0, -0.25]}
                          rotation={[Math.PI / 6, 0, 0]}>
                          <group name="cube_65" position={[-0.716, -0.048, -0.708]}>
                            <mesh
                              name="Object_109"
                              castShadow
                              receiveShadow
                              geometry={nodes.Object_109.geometry}
                              material={materials.material_0}
                            />
                          </group>
                          <group
                            name="hand1pieceaddonpart4_73"
                            position={[0, 0, -0.25]}
                            rotation={[Math.PI / 4, 0, 0]}>
                            <group name="cube_66" position={[-0.716, -0.1, -0.635]}>
                              <mesh
                                name="Object_112"
                                castShadow
                                receiveShadow
                                geometry={nodes.Object_112.geometry}
                                material={materials.material_0}
                              />
                            </group>
                            <group
                              name="hand1pieceaddonpartend4_70"
                              position={[-0.063, 0, -0.188]}
                              rotation={[Math.PI / 3, 0, 0]}>
                              <group name="cube_67" position={[-0.654, -0.1, -0.572]}>
                                <mesh
                                  name="Object_115"
                                  castShadow
                                  receiveShadow
                                  geometry={nodes.Object_115.geometry}
                                  material={materials.material_0}
                                />
                              </group>
                              <group
                                name="hand1pieceaddonpartendsculk4_69"
                                position={[0.063, 0, 0]}>
                                <group name="cube_68" position={[-0.466, -0.1, -1.635]}>
                                  <mesh
                                    name="Object_118"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Object_118.geometry}
                                    material={materials.material_0}
                                  />
                                </group>
                              </group>
                            </group>
                            <group
                              name="hand1pieceaddonpartsculk4_72"
                              position={[0.063, 1.188, 0.125]}>
                              <group name="cube_71" position={[-0.529, -1.287, -1.572]}>
                                <mesh
                                  name="Object_121"
                                  castShadow
                                  receiveShadow
                                  geometry={nodes.Object_121.geometry}
                                  material={materials.material_0}
                                />
                              </group>
                            </group>
                          </group>
                          <group name="hand1pieceaddonsculk4_75" position={[0.125, 0.563, 0.75]}>
                            <group name="cube_74" position={[-0.591, -0.611, -2.021]}>
                              <mesh
                                name="Object_124"
                                castShadow
                                receiveShadow
                                geometry={nodes.Object_124.geometry}
                                material={materials.material_0}
                              />
                            </group>
                          </group>
                        </group>
                        <group name="hand1piecesculk4_78" position={[0.063, -0.063, 0.625]}>
                          <group name="cube_77" position={[-0.529, 0.014, -1.617]}>
                            <mesh
                              name="Object_127"
                              castShadow
                              receiveShadow
                              geometry={nodes.Object_127.geometry}
                              material={materials.material_0}
                            />
                          </group>
                        </group>
                      </group>
                      <group name="hand1sculk4_81" position={[0.25, -0.063, 0.25]}>
                        <group name="cube_80" position={[-0.011, 0, 0.036]}>
                          <mesh
                            name="Object_130"
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_130.geometry}
                            material={materials.material_0}
                          />
                        </group>
                      </group>
                    </group>
                    <group
                      name="hand5_102"
                      position={[0.313, 0.063, 0.25]}
                      rotation={[Math.PI, -0.611, Math.PI]}>
                      <group name="cube_83" position={[-0.313, -0.063, 0.25]}>
                        <mesh
                          name="Object_133"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_133.geometry}
                          material={materials.material_0}
                        />
                      </group>
                      <group
                        name="hand1piece5_99"
                        position={[0, 0, -0.25]}
                        rotation={[0.35, 0.082, -0.03]}>
                        <group name="cube_84" position={[-0.313, -0.063, 0.5]}>
                          <mesh
                            name="Object_136"
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_136.geometry}
                            material={materials.material_0}
                          />
                        </group>
                        <group
                          name="hand1pieceaddon5_96"
                          position={[0, 0, -0.25]}
                          rotation={[Math.PI / 6, 0, 0]}>
                          <group name="cube_85" position={[-0.313, -0.063, 0.563]}>
                            <mesh
                              name="Object_139"
                              castShadow
                              receiveShadow
                              geometry={nodes.Object_139.geometry}
                              material={materials.material_0}
                            />
                          </group>
                          <group
                            name="hand1pieceaddonpart5_93"
                            position={[0, 0, -0.25]}
                            rotation={[Math.PI / 4, 0, 0]}>
                            <group name="cube_86" position={[-0.313, -0.063, 0.813]}>
                              <mesh
                                name="Object_142"
                                castShadow
                                receiveShadow
                                geometry={nodes.Object_142.geometry}
                                material={materials.material_0}
                              />
                            </group>
                            <group
                              name="hand1pieceaddonpartend5_90"
                              position={[0, 0, -0.188]}
                              rotation={[Math.PI / 3, 0, 0]}>
                              <group name="cube_87" position={[-0.313, -0.063, 1]}>
                                <mesh
                                  name="Object_145"
                                  castShadow
                                  receiveShadow
                                  geometry={nodes.Object_145.geometry}
                                  material={materials.material_0}
                                />
                              </group>
                              <group name="hand1pieceaddonpartendsculk5_89">
                                <group name="cube_88">
                                  <mesh
                                    name="Object_148"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Object_148.geometry}
                                    material={materials.material_0}
                                  />
                                </group>
                              </group>
                            </group>
                            <group name="hand1pieceaddonpartsculk5_92" position={[0.063, 1, 0.25]}>
                              <group name="cube_91" position={[-0.063, -1, -0.25]}>
                                <mesh
                                  name="Object_151"
                                  castShadow
                                  receiveShadow
                                  geometry={nodes.Object_151.geometry}
                                  material={materials.material_0}
                                />
                              </group>
                            </group>
                          </group>
                          <group name="hand1pieceaddonsculk5_95" position={[0, 0.563, 0.688]}>
                            <group name="cube_94" position={[0, -0.563, -0.688]}>
                              <mesh
                                name="Object_154"
                                castShadow
                                receiveShadow
                                geometry={nodes.Object_154.geometry}
                                material={materials.material_0}
                              />
                            </group>
                          </group>
                        </group>
                        <group name="hand1piecesculk5_98" position={[0, 0, 0.625]}>
                          <group name="cube_97" position={[0, 0, -0.625]}>
                            <mesh
                              name="Object_157"
                              castShadow
                              receiveShadow
                              geometry={nodes.Object_157.geometry}
                              material={materials.material_0}
                            />
                          </group>
                        </group>
                      </group>
                      <group name="hand1sculk5_101" position={[-0.313, -0.063, 0.25]}>
                        <group name="cube_100" position={[0, 0, -0.5]}>
                          <mesh
                            name="Object_160"
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_160.geometry}
                            material={materials.material_0}
                          />
                        </group>
                      </group>
                    </group>
                    <group
                      name="hand6_122"
                      position={[0.125, 0.063, 0.313]}
                      rotation={[Math.PI, -0.262, Math.PI]}>
                      <group name="cube_103" position={[-0.313, -0.063, 0.25]}>
                        <mesh
                          name="Object_163"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_163.geometry}
                          material={materials.material_0}
                        />
                      </group>
                      <group
                        name="hand1piece6_119"
                        position={[0, 0, -0.25]}
                        rotation={[Math.PI / 9, 0, 0]}>
                        <group name="cube_104" position={[-0.313, -0.063, 0.5]}>
                          <mesh
                            name="Object_166"
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_166.geometry}
                            material={materials.material_0}
                          />
                        </group>
                        <group
                          name="hand1pieceaddon6_116"
                          position={[0, 0, -0.25]}
                          rotation={[Math.PI / 6, 0, 0]}>
                          <group name="cube_105" position={[-0.313, -0.063, 0.563]}>
                            <mesh
                              name="Object_169"
                              castShadow
                              receiveShadow
                              geometry={nodes.Object_169.geometry}
                              material={materials.material_0}
                            />
                          </group>
                          <group
                            name="hand1pieceaddonpart6_113"
                            position={[0, 0, -0.25]}
                            rotation={[Math.PI / 4, 0, 0]}>
                            <group name="cube_106" position={[-0.313, -0.063, 0.813]}>
                              <mesh
                                name="Object_172"
                                castShadow
                                receiveShadow
                                geometry={nodes.Object_172.geometry}
                                material={materials.material_0}
                              />
                            </group>
                            <group
                              name="hand1pieceaddonpartend6_110"
                              position={[0, 0, -0.188]}
                              rotation={[Math.PI / 3, 0, 0]}>
                              <group name="cube_107" position={[-0.313, -0.063, 1]}>
                                <mesh
                                  name="Object_175"
                                  castShadow
                                  receiveShadow
                                  geometry={nodes.Object_175.geometry}
                                  material={materials.material_0}
                                />
                              </group>
                              <group name="hand1pieceaddonpartendsculk6_109">
                                <group name="cube_108">
                                  <mesh
                                    name="Object_178"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Object_178.geometry}
                                    material={materials.material_0}
                                  />
                                </group>
                              </group>
                            </group>
                            <group
                              name="hand1pieceaddonpartsculk6_112"
                              position={[0.063, 1.063, 0.125]}>
                              <group name="cube_111" position={[-0.063, -1.063, -0.125]}>
                                <mesh
                                  name="Object_181"
                                  castShadow
                                  receiveShadow
                                  geometry={nodes.Object_181.geometry}
                                  material={materials.material_0}
                                />
                              </group>
                            </group>
                          </group>
                          <group name="hand1pieceaddonsculk6_115" position={[0.188, 0.625, 0.625]}>
                            <group name="cube_114" position={[-0.188, -0.625, -0.625]}>
                              <mesh
                                name="Object_184"
                                castShadow
                                receiveShadow
                                geometry={nodes.Object_184.geometry}
                                material={materials.material_0}
                              />
                            </group>
                          </group>
                        </group>
                        <group name="hand1piecesculk6_118" position={[0.063, 0, 0.625]}>
                          <group name="cube_117" position={[-0.063, 0, -0.625]}>
                            <mesh
                              name="Object_187"
                              castShadow
                              receiveShadow
                              geometry={nodes.Object_187.geometry}
                              material={materials.material_0}
                            />
                          </group>
                        </group>
                      </group>
                      <group name="hand1sculk6_121" position={[-0.313, -0.063, 0.25]}>
                        <group name="cube_120" position={[0.188, 0, -0.563]}>
                          <mesh
                            name="Object_190"
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_190.geometry}
                            material={materials.material_0}
                          />
                        </group>
                      </group>
                    </group>
                    <group
                      name="hand7_142"
                      position={[-0.125, 0.063, 0.313]}
                      rotation={[-Math.PI, 0.262, -Math.PI]}>
                      <group name="cube_123" position={[-0.313, -0.063, 0.25]}>
                        <mesh
                          name="Object_193"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_193.geometry}
                          material={materials.material_0}
                        />
                      </group>
                      <group
                        name="hand1piece7_139"
                        position={[0, 0, -0.25]}
                        rotation={[Math.PI / 9, 0, 0]}>
                        <group name="cube_124" position={[-0.313, -0.063, 0.5]}>
                          <mesh
                            name="Object_196"
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_196.geometry}
                            material={materials.material_0}
                          />
                        </group>
                        <group
                          name="hand1pieceaddon7_136"
                          position={[0, 0, -0.25]}
                          rotation={[Math.PI / 6, 0, 0]}>
                          <group name="cube_125" position={[-0.313, -0.063, 0.563]}>
                            <mesh
                              name="Object_199"
                              castShadow
                              receiveShadow
                              geometry={nodes.Object_199.geometry}
                              material={materials.material_0}
                            />
                          </group>
                          <group
                            name="hand1pieceaddonpart7_133"
                            position={[0, 0, -0.25]}
                            rotation={[Math.PI / 4, 0, 0]}>
                            <group name="cube_126" position={[-0.313, -0.063, 0.813]}>
                              <mesh
                                name="Object_202"
                                castShadow
                                receiveShadow
                                geometry={nodes.Object_202.geometry}
                                material={materials.material_0}
                              />
                            </group>
                            <group
                              name="hand1pieceaddonpartend7_130"
                              position={[0, 0, -0.188]}
                              rotation={[Math.PI / 3, 0, 0]}>
                              <group name="cube_127" position={[-0.313, -0.063, 1]}>
                                <mesh
                                  name="Object_205"
                                  castShadow
                                  receiveShadow
                                  geometry={nodes.Object_205.geometry}
                                  material={materials.material_0}
                                />
                              </group>
                              <group name="hand1pieceaddonpartendsculk7_129">
                                <group name="cube_128">
                                  <mesh
                                    name="Object_208"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Object_208.geometry}
                                    material={materials.material_0}
                                  />
                                </group>
                              </group>
                            </group>
                            <group
                              name="hand1pieceaddonpartsculk7_132"
                              position={[-0.125, 0.938, 0.25]}>
                              <group name="cube_131" position={[0.125, -0.938, -0.25]}>
                                <mesh
                                  name="Object_211"
                                  castShadow
                                  receiveShadow
                                  geometry={nodes.Object_211.geometry}
                                  material={materials.material_0}
                                />
                              </group>
                            </group>
                          </group>
                          <group name="hand1pieceaddonsculk7_135" position={[-0.063, 0.5, 0.688]}>
                            <group name="cube_134" position={[0.063, -0.5, -0.688]}>
                              <mesh
                                name="Object_214"
                                castShadow
                                receiveShadow
                                geometry={nodes.Object_214.geometry}
                                material={materials.material_0}
                              />
                            </group>
                          </group>
                        </group>
                        <group name="hand1piecesculk7_138" position={[0, 0, 0.75]}>
                          <group name="cube_137" position={[0, 0, -0.75]}>
                            <mesh
                              name="Object_217"
                              castShadow
                              receiveShadow
                              geometry={nodes.Object_217.geometry}
                              material={materials.material_0}
                            />
                          </group>
                        </group>
                      </group>
                      <group name="hand1sculk7_141" position={[-0.313, -0.063, 0.25]}>
                        <group name="cube_140" position={[0.438, 0, -0.563]}>
                          <mesh
                            name="Object_220"
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_220.geometry}
                            material={materials.material_0}
                          />
                        </group>
                      </group>
                    </group>
                    <group
                      name="hand8_162"
                      position={[-0.313, 0.063, 0.25]}
                      rotation={[-Math.PI, 0.611, -Math.PI]}>
                      <group name="cube_143" position={[-0.313, -0.063, 0.25]}>
                        <mesh
                          name="Object_223"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_223.geometry}
                          material={materials.material_0}
                        />
                      </group>
                      <group
                        name="hand1piece8_159"
                        position={[0, 0, -0.25]}
                        rotation={[0.35, -0.082, 0.03]}>
                        <group name="cube_144" position={[-0.313, -0.063, 0.5]}>
                          <mesh
                            name="Object_226"
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_226.geometry}
                            material={materials.material_0}
                          />
                        </group>
                        <group
                          name="hand1pieceaddon8_156"
                          position={[0, 0, -0.25]}
                          rotation={[Math.PI / 6, 0, 0]}>
                          <group name="cube_145" position={[-0.313, -0.063, 0.563]}>
                            <mesh
                              name="Object_229"
                              castShadow
                              receiveShadow
                              geometry={nodes.Object_229.geometry}
                              material={materials.material_0}
                            />
                          </group>
                          <group
                            name="hand1pieceaddonpart8_153"
                            position={[0, 0, -0.25]}
                            rotation={[Math.PI / 4, 0, 0]}>
                            <group name="cube_146" position={[-0.313, -0.063, 0.813]}>
                              <mesh
                                name="Object_232"
                                castShadow
                                receiveShadow
                                geometry={nodes.Object_232.geometry}
                                material={materials.material_0}
                              />
                            </group>
                            <group
                              name="hand1pieceaddonpartend8_150"
                              position={[0, 0, -0.188]}
                              rotation={[Math.PI / 3, 0, 0]}>
                              <group name="cube_147" position={[-0.313, -0.063, 1]}>
                                <mesh
                                  name="Object_235"
                                  castShadow
                                  receiveShadow
                                  geometry={nodes.Object_235.geometry}
                                  material={materials.material_0}
                                />
                              </group>
                              <group name="hand1pieceaddonpartendsculk8_149">
                                <group name="cube_148">
                                  <mesh
                                    name="Object_238"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Object_238.geometry}
                                    material={materials.material_0}
                                  />
                                </group>
                              </group>
                            </group>
                            <group
                              name="hand1pieceaddonpartsculk8_152"
                              position={[-1, 1.625, 0.563]}>
                              <group name="cube_151" position={[1, -1.625, -0.563]}>
                                <mesh
                                  name="Object_241"
                                  castShadow
                                  receiveShadow
                                  geometry={nodes.Object_241.geometry}
                                  material={materials.material_0}
                                />
                              </group>
                            </group>
                          </group>
                          <group name="hand1pieceaddonsculk8_155" position={[-0.188, 0.625, 0.75]}>
                            <group name="cube_154" position={[0.188, -0.625, -0.75]}>
                              <mesh
                                name="Object_244"
                                castShadow
                                receiveShadow
                                geometry={nodes.Object_244.geometry}
                                material={materials.material_0}
                              />
                            </group>
                          </group>
                        </group>
                        <group name="hand1piecesculk8_158" position={[0, 0, 0.625]}>
                          <group name="cube_157" position={[0, 0, -0.625]}>
                            <mesh
                              name="Object_247"
                              castShadow
                              receiveShadow
                              geometry={nodes.Object_247.geometry}
                              material={materials.material_0}
                            />
                          </group>
                        </group>
                      </group>
                      <group name="hand1sculk8_161" position={[-0.313, -0.063, 0.25]}>
                        <group name="cube_160" position={[0.625, 0, -0.5]}>
                          <mesh
                            name="Object_250"
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_250.geometry}
                            material={materials.material_0}
                          />
                        </group>
                      </group>
                    </group>
                  </group>
                  <group name="head_177">
                    <group name="cube_164">
                      <mesh
                        name="Object_253"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_253.geometry}
                        material={materials.material_0}
                      />
                    </group>
                    <group name="cube_165">
                      <mesh
                        name="Object_255"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_255.geometry}
                        material={materials.material_0}
                      />
                    </group>
                    <group name="cube_166">
                      <mesh
                        name="Object_257"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_257.geometry}
                        material={materials.material_0}
                      />
                    </group>
                    <group name="cube_167">
                      <mesh
                        name="Object_259"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_259.geometry}
                        material={materials.material_0}
                      />
                    </group>
                    <group name="headsculk_176">
                      <group name="cube_168">
                        <mesh
                          name="Object_262"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_262.geometry}
                          material={materials.material_0}
                        />
                      </group>
                      <group name="eye_sculk_173">
                        <group name="left_eye_170">
                          <group name="cube_169">
                            <mesh
                              name="Object_266"
                              castShadow
                              receiveShadow
                              geometry={nodes.Object_266.geometry}
                              material={materials.material_0}
                            />
                          </group>
                        </group>
                        <group name="right_eye_172">
                          <group name="cube_171">
                            <mesh
                              name="Object_269"
                              castShadow
                              receiveShadow
                              geometry={nodes.Object_269.geometry}
                              material={materials.material_0}
                            />
                          </group>
                        </group>
                      </group>
                      <group name="wind_175" position={[-0.688, 0.25, -0.25]}>
                        <group name="cube_174">
                          <mesh
                            name="Object_272"
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_272.geometry}
                            material={materials.material_0}
                          />
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

export default Octopus
