/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Treeminator (https://sketchfab.com/Treeminator)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/blockbench-whale-free-acb401ed24e24ca295fb87042720c4ac
Title: Blockbench Whale (free)
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

import scene from '../assets/3d/whale.glb'

const Whale=({currentAnimation,...props}) => {


  const group = useRef()
  const { nodes, materials, animations } = useGLTF(scene)
  const { actions } = useAnimations(animations, group)



  useEffect(()=>{

  },[actions,currentAnimation])



  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="_55">
                <group name="All_54">
                  <group name="Body_53" position={[0, 0.75, 0.75]}>
                    <group name="cube_0" position={[0.313, -0.75, -0.75]}>
                      <mesh
                        name="Object_7"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_7.geometry}
                        material={materials.material_0}
                      />
                    </group>
                    <group name="cube_1" rotation={[0.044, 0, 0]}>
                      <mesh
                        name="Object_9"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_9.geometry}
                        material={materials.material_0}
                      />
                    </group>
                    <group name="Back_31" position={[0.014, -0.049, -0.078]}>
                      <group
                        name="cube_2"
                        position={[-0.014, 0.179, 1.077]}
                        rotation={[0.044, 0, 0]}>
                        <mesh
                          name="Object_12"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_12.geometry}
                          material={materials.material_0}
                        />
                      </group>
                      <group
                        name="cube_3"
                        position={[0.298, -0.701, -0.672]}
                        rotation={[-0.175, 0, 0]}>
                        <mesh
                          name="Object_14"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_14.geometry}
                          material={materials.material_0}
                        />
                      </group>
                      <group name="Backfin_8" position={[-0.014, 0.62, -0.085]}>
                        <group name="cube_4" rotation={[Math.PI / 3, 0, 0]}>
                          <mesh
                            name="Object_17"
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_17.geometry}
                            material={materials.material_0}
                          />
                        </group>
                        <group name="cube_5" position={[0, 0.219, 0.379]} rotation={[1.353, 0, 0]}>
                          <mesh
                            name="Object_19"
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_19.geometry}
                            material={materials.material_0}
                          />
                        </group>
                        <group
                          name="cube_6"
                          position={[0, 0.205, 0.752]}
                          rotation={[1.655, -0.014, 0.007]}>
                          <mesh
                            name="Object_21"
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_21.geometry}
                            material={materials.material_0}
                          />
                        </group>
                        <group name="cube_7" position={[0, 0.259, 0.562]} rotation={[1.527, 0, 0]}>
                          <mesh
                            name="Object_23"
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_23.geometry}
                            material={materials.material_0}
                          />
                        </group>
                      </group>
                      <group name="Tail_30" position={[-0.014, -0.037, 1.092]}>
                        <group name="cube_9" position={[0, 0.123, 1.019]}>
                          <mesh
                            name="Object_26"
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_26.geometry}
                            material={materials.material_0}
                          />
                        </group>
                        <group name="cube_10" position={[0, 0, 0.563]} rotation={[-0.131, 0, 0]}>
                          <mesh
                            name="Object_28"
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_28.geometry}
                            material={materials.material_0}
                          />
                        </group>
                        <group name="Tail2_29" position={[0, 0.086, 0.949]}>
                          <group
                            name="cube_11"
                            position={[0, 0.125, 0.5]}
                            rotation={[-0.044, 0, 0]}>
                            <mesh
                              name="Object_31"
                              castShadow
                              receiveShadow
                              geometry={nodes.Object_31.geometry}
                              material={materials.material_0}
                            />
                          </group>
                          <group name="Tail3_28" position={[0, 0.095, 0.752]}>
                            <group name="cube_12" position={[0, 0, 0.5]} rotation={[-0.131, 0, 0]}>
                              <mesh
                                name="Object_34"
                                castShadow
                                receiveShadow
                                geometry={nodes.Object_34.geometry}
                                material={materials.material_0}
                              />
                            </group>
                            <group name="Tail4_27" position={[0.003, 0.152, 0.828]}>
                              <group
                                name="cube_13"
                                position={[-0.003, -0.018, -0.03]}
                                rotation={[-0.083, 0.017, 0.022]}>
                                <mesh
                                  name="Object_37"
                                  castShadow
                                  receiveShadow
                                  geometry={nodes.Object_37.geometry}
                                  material={materials.material_0}
                                />
                              </group>
                              <group name="Fin_26" position={[-0.191, -0.067, -0.402]}>
                                <group
                                  name="cube_14"
                                  position={[0.375, 0, 0]}
                                  rotation={[-0.131, 0.742, 0]}>
                                  <mesh
                                    name="Object_40"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Object_40.geometry}
                                    material={materials.material_0}
                                  />
                                </group>
                                <group
                                  name="cube_15"
                                  position={[-0.23, 0.105, 0.799]}
                                  rotation={[-0.131, -Math.PI / 3, 0]}>
                                  <mesh
                                    name="Object_42"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Object_42.geometry}
                                    material={materials.material_0}
                                  />
                                </group>
                                <group
                                  name="cube_16"
                                  position={[0.605, 0.105, 0.799]}
                                  rotation={[-0.131, Math.PI / 3, 0]}>
                                  <mesh
                                    name="Object_44"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Object_44.geometry}
                                    material={materials.material_0}
                                  />
                                </group>
                                <group
                                  name="cube_17"
                                  position={[-0.851, 0.095, 0.725]}
                                  rotation={[-0.131, -Math.PI / 4, 0]}>
                                  <mesh
                                    name="Object_46"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Object_46.geometry}
                                    material={materials.material_0}
                                  />
                                </group>
                                <group
                                  name="cube_18"
                                  position={[1.668, 0.153, 1.163]}
                                  rotation={[-0.131, -0.305, 0]}>
                                  <mesh
                                    name="Object_48"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Object_48.geometry}
                                    material={materials.material_0}
                                  />
                                </group>
                                <group
                                  name="cube_19"
                                  position={[-1.293, 0.153, 1.163]}
                                  rotation={[-0.131, 0.305, 0]}>
                                  <mesh
                                    name="Object_50"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Object_50.geometry}
                                    material={materials.material_0}
                                  />
                                </group>
                                <group name="cube_20" rotation={[-0.131, -0.742, 0]}>
                                  <mesh
                                    name="Object_52"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Object_52.geometry}
                                    material={materials.material_0}
                                  />
                                </group>
                                <group
                                  name="cube_21"
                                  position={[1.357, 0.2, 1.521]}
                                  rotation={[-0.131, -Math.PI / 8, 0]}>
                                  <mesh
                                    name="Object_54"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Object_54.geometry}
                                    material={materials.material_0}
                                  />
                                </group>
                                <group
                                  name="cube_22"
                                  position={[-0.578, 0.178, 1.355]}
                                  rotation={[-0.131, 0.262, 0]}>
                                  <mesh
                                    name="Object_56"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Object_56.geometry}
                                    material={materials.material_0}
                                  />
                                </group>
                                <group
                                  name="cube_23"
                                  position={[1.226, 0.095, 0.725]}
                                  rotation={[-0.131, Math.PI / 4, 0]}>
                                  <mesh
                                    name="Object_58"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Object_58.geometry}
                                    material={materials.material_0}
                                  />
                                </group>
                                <group
                                  name="cube_24"
                                  position={[-0.982, 0.2, 1.521]}
                                  rotation={[-0.131, Math.PI / 8, 0]}>
                                  <mesh
                                    name="Object_60"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Object_60.geometry}
                                    material={materials.material_0}
                                  />
                                </group>
                                <group
                                  name="cube_25"
                                  position={[0.953, 0.178, 1.355]}
                                  rotation={[-0.131, -0.262, 0]}>
                                  <mesh
                                    name="Object_62"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Object_62.geometry}
                                    material={materials.material_0}
                                  />
                                </group>
                              </group>
                            </group>
                          </group>
                        </group>
                      </group>
                    </group>
                    <group name="Finleft_37" position={[-0.5, -0.094, -0.969]}>
                      <group
                        name="cube_32"
                        position={[-0.453, -0.329, -0.034]}
                        rotation={[-0.273, 0.4, 0.623]}>
                        <mesh
                          name="Object_65"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_65.geometry}
                          material={materials.material_0}
                        />
                      </group>
                      <group
                        name="cube_33"
                        position={[-1.57, -1.04, 1.077]}
                        rotation={[-0.168, 0.256, 0.589]}>
                        <mesh
                          name="Object_67"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_67.geometry}
                          material={materials.material_0}
                        />
                      </group>
                      <group
                        name="cube_34"
                        position={[-0.316, -0.241, 0.805]}
                        rotation={[-0.493, 0.639, 0.733]}>
                        <mesh
                          name="Object_69"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_69.geometry}
                          material={materials.material_0}
                        />
                      </group>
                      <group
                        name="cube_35"
                        position={[-1.716, -1.133, 0.745]}
                        rotation={[-1.331, 0.99, 1.369]}>
                        <mesh
                          name="Object_71"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_71.geometry}
                          material={materials.material_0}
                        />
                      </group>
                      <group
                        name="cube_36"
                        position={[0, 0.016, 0.484]}
                        rotation={[-0.094, 0.147, 0.574]}>
                        <mesh
                          name="Object_73"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_73.geometry}
                          material={materials.material_0}
                        />
                      </group>
                    </group>
                    <group name="Finright_43" position={[0.5, -0.078, -0.984]}>
                      <group
                        name="cube_38"
                        position={[0.453, -0.344, -0.019]}
                        rotation={[-0.273, -0.4, -0.623]}>
                        <mesh
                          name="Object_76"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_76.geometry}
                          material={materials.material_0}
                        />
                      </group>
                      <group
                        name="cube_39"
                        position={[0, 0, 0.5]}
                        rotation={[-0.094, -0.147, -0.574]}>
                        <mesh
                          name="Object_78"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_78.geometry}
                          material={materials.material_0}
                        />
                      </group>
                      <group
                        name="cube_40"
                        position={[1.716, -1.149, 0.76]}
                        rotation={[-1.331, -0.99, -1.369]}>
                        <mesh
                          name="Object_80"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_80.geometry}
                          material={materials.material_0}
                        />
                      </group>
                      <group
                        name="cube_41"
                        position={[0.316, -0.257, 0.821]}
                        rotation={[-0.493, -0.639, -0.733]}>
                        <mesh
                          name="Object_82"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_82.geometry}
                          material={materials.material_0}
                        />
                      </group>
                      <group
                        name="cube_42"
                        position={[1.57, -1.056, 1.093]}
                        rotation={[-0.168, -0.256, -0.589]}>
                        <mesh
                          name="Object_84"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_84.geometry}
                          material={materials.material_0}
                        />
                      </group>
                    </group>
                    <group name="Head_52" position={[0, 0.494, -1.292]}>
                      <group name="cube_44">
                        <mesh
                          name="Object_87"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_87.geometry}
                          material={materials.material_0}
                        />
                      </group>
                      <group
                        name="cube_45"
                        position={[0.438, -0.25, -0.813]}
                        rotation={[0, 0.087, 0]}>
                        <mesh
                          name="Object_89"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_89.geometry}
                          material={materials.material_0}
                        />
                      </group>
                      <group name="cube_46" position={[-0.312, -0.25, -2.245]}>
                        <mesh
                          name="Object_91"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_91.geometry}
                          material={materials.material_0}
                        />
                      </group>
                      <group
                        name="cube_47"
                        position={[-0.438, -0.25, -0.813]}
                        rotation={[0, -0.087, 0]}>
                        <mesh
                          name="Object_93"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_93.geometry}
                          material={materials.material_0}
                        />
                      </group>
                      <group name="cube_48" position={[0, 0, -2.245]} rotation={[-0.044, 0, 0]}>
                        <mesh
                          name="Object_95"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_95.geometry}
                          material={materials.material_0}
                        />
                      </group>
                      <group name="Bottom_51" position={[0, -0.538, 0.046]}>
                        <group name="cube_49" position={[0, -0.375, -1]}>
                          <mesh
                            name="Object_98"
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_98.geometry}
                            material={materials.material_0}
                          />
                        </group>
                        <group
                          name="cube_50"
                          position={[0, -0.519, -0.066]}
                          rotation={[0.087, 0, 0]}>
                          <mesh
                            name="Object_100"
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_100.geometry}
                            material={materials.material_0}
                          />
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

export default Whale
